import { arSA, enUS, esES, faIR, frFR, hiIN, zhCN } from '@mui/material/locale';
import {
	ar,
	enUS as en,
	es,
	faIR as fa,
	fr,
	hi,
	zhCN as zh,
} from 'date-fns/locale';
import { DirectionEnum, Flag, LanguageCodeEnum } from 'src/constants';
import { Languages } from 'src/types';

export const LocalizationLanguages: Languages = {
	ar: {
		code: LanguageCodeEnum.ar,
		direction: DirectionEnum.rtl,
		flag: Flag.ar,
		fns: ar,
		fonts: ['Cairo'],
		isoCode: 'ar_AR',
		label: 'عربى',
		localization: arSA,
	},
	en: {
		code: LanguageCodeEnum.en,
		direction: DirectionEnum.ltr,
		flag: Flag.en,
		fns: en,
		fonts: ['Poppins'],
		isoCode: 'en_US',
		label: 'English',
		localization: enUS,
	},
	es: {
		code: LanguageCodeEnum.es,
		direction: DirectionEnum.ltr,
		flag: Flag.es,
		fns: es,
		fonts: ['Poppins'],
		isoCode: 'es',
		label: 'española',
		localization: esES,
	},
	fa: {
		code: LanguageCodeEnum.fa,
		direction: DirectionEnum.rtl,
		flag: Flag.fa,
		fns: fa,
		fonts: ['Cairo'],
		isoCode: 'fa_IR',
		label: 'فارسی',
		localization: faIR,
	},
	fr: {
		code: LanguageCodeEnum.fr,
		direction: DirectionEnum.ltr,
		flag: Flag.fr,
		fns: fr,
		fonts: ['Poppins'],
		isoCode: 'fr',
		label: 'Français',
		localization: frFR,
	},
	hi: {
		code: LanguageCodeEnum.hi,
		direction: DirectionEnum.ltr,
		flag: Flag.hi,
		fns: hi,
		fonts: ['Poppins'],
		isoCode: 'hi_IN',
		label: 'हिंदी',
		localization: hiIN,
	},
	zh: {
		code: LanguageCodeEnum.zh,
		direction: DirectionEnum.ltr,
		flag: Flag.zh,
		fns: zh,
		fonts: ['Poppins'],
		isoCode: 'zh',
		label: '中华人民共和国',
		localization: zhCN,
	},
};
