export const JoinTables = [
	'join_broker_feedback',
	'join_certification_documents',
	'join_department_employees',
	'join_employee_documents',
	'join_employee_health_conditions',
	'join_employee_nationalities',
	'join_entity_employees',
	'join_expense_documents',
	'join_factory_countries',
	'join_factory_feedback',
	'join_health_condition_documents',
	'join_health_condition_medications',
	'join_insurance_company_feedback',
	'join_insurance_company_insurance_types',
	'join_marriage_documents',
	'join_marriage_kids',
	'join_offer_plan_providers',
	'join_product_documents',
	'join_product_product_categories',
	'join_product_product_type_attribute_values',
	'join_product_warehouses',
	'join_provider_type',
	'join_relative_documents',
	'join_relative_health_conditions',
	'join_request_documents',
	'join_role_employees',
	'join_ship_line_ports',
	'join_shipping_company_countries',
	'join_training_trainees',
	'join_training_trainers',
] as const;

export const nonJoinTable = [
	'addresses',
	'advances',
	'allowances',
	'announcements',
	'bonuses',
	'certifications',
	'commissions',
	'contact_information',
	'contracts',
	'deductions',
	'departments',
	'driver_licenses',
	'emergency_contacts',
	'employee_reports',
	'employees',
	'expenses',
	'health_reports',
	'identification_cards',
	'images',
	'insurance_reports',
	'job_titles',
	'jsonschema_validators',
	'options',
	'passports',
	'payroll_deductions',
	'res_cities',
	'res_countries',
	'res_currencies',
	'residencies',
	'sponsors',
	'status_histories',
	'survey_answers',
	'surveys',
	'types',
	'vacations',
	'visas',
	'work_hours',
	'work_locations',
] as const;

export const entities = ['entities', 'entity_types', 'policies'] as const;

export const complaints = ['base_complaints', 'complaints'] as const;

export const proposals = ['base_proposals', 'proposals'] as const;

export const requests = [
	'base_requests',
	'request_advances',
	'request_allowances',
	'request_benefits',
	'request_bonuses',
	'request_commissions',
	'request_delegations',
	'request_external_delegations',
	'request_internal_delegations',
	'request_expenses',
	'request_installments',
	'request_payroll_deductions_cancels',
	'request_permissions',
	'request_promotions',
	'request_punctuality_changes',
	'request_purchases',
	'request_resignations',
	'request_retirement_age_extensions',
	'request_salary_raises',
	'request_settlements',
	'request_transfers',
	'request_vacations',
	'request_work_hours_changes',
	'requests',
] as const;

export const beneficiaries = [
	'beneficiaries',
	'kids',
	'relatives',
	'spouses',
] as const;
