export const nationalities = {
	AD: 'Andorran',
	AE: 'Emirian',
	AF: 'Afghan',
	AG: 'Antiguans',
	AL: 'Albanian',
	AM: 'Armenian',
	AO: 'Angolan',
	AR: 'Argentinean',
	AT: 'Austrian',
	AU: 'Australian',
	AX: 'Åland Islands',
	AZ: 'Azerbaijani',
	BA: 'Bosnian - Herzegovinian',
	BB: 'Barbadian',
	BD: 'Bangladeshi',
	BE: 'Belgian',
	BF: 'Burkinabe',
	BG: 'Bulgarian',
	BH: 'Bahraini',
	BI: 'Burundian',
	BJ: 'Beninese',
	BL: 'Saint Barthélemy',
	BM: 'Bermuda',
	BN: 'Bruneian',
	BO: 'Bolivian',
	BQ: 'Bonaire, Sint Eustatius and Saba',
	BR: 'Brazilian',
	BS: 'Bahamian',
	BT: 'Bhutanese',
	BV: 'Bouvet Island',
	BW: 'Batswana',
	BY: 'Belarusian',
	BZ: 'Belizean',
	CA: 'Canadian',
	CC: 'Cocos (Keeling) Islands',
	CD: 'Congolese (Democratic Republic of the Congo)',
	CF: 'Central African',
	CG: 'Congolese (Republic of the Congo)',
	CH: 'Swiss',
	CI: 'Ivorian',
	CK: 'Cook Islands',
	CL: 'Chilean',
	CM: 'Cameroonian',
	CN: 'Chinese',
	CO: 'Colombian',
	CR: 'Costa Rican',
	CU: 'Cuban',
	CV: 'Cape Verdean',
	CW: 'Curaçao',
	CX: 'Christmas Island',
	CY: 'Cypriot',
	CZ: 'Czech',
	DE: 'German',
	DJ: 'Djibouti',
	DK: 'Danish',
	DM: 'Dominican (Dominica)',
	DO: 'Dominican (Dominican Republic)',
	DZ: 'Algerian',
	EC: 'Ecuadorean',
	EE: 'Estonian',
	EG: 'Egyptian',
	EH: 'Western Sahara',
	ER: 'Eritrean',
	ES: 'Spanish',
	ET: 'Ethiopian',
	FI: 'Finnish',
	FJ: 'Fijian',
	FK: 'Falkland Islands (Malvinas)',
	FM: 'Micronesian',
	FO: 'Faroe Islands',
	FR: 'French',
	GA: 'Gabonese',
	GB: 'British',
	GD: 'Grenadian',
	GE: 'Georgian',
	GF: 'French (French Guiana)',
	GG: 'Guernsey',
	GH: 'Ghanaian',
	GI: 'Gibraltar',
	GL: 'Greenland',
	GM: 'Gambian',
	GN: 'Guinean',
	GP: 'Guadeloupe',
	GQ: 'Equatorial Guinean',
	GR: 'Greek',
	GS: 'South Georgia and the South Sandwich Islands',
	GT: 'Guatemalan',
	GU: 'Guam',
	GW: 'Guinea-Bissauan',
	GY: 'Guyanese',
	HK: 'Hong Kong',
	HM: 'Heard Island and Mcdonald Islands',
	HN: 'Honduran',
	HR: 'Croatian',
	HT: 'Haitian',
	HU: 'Hungarian',
	ID: 'Indonesian',
	IE: 'Irish',
	IL: 'Israeli',
	IM: 'Manx',
	IN: 'Indian',
	IO: 'British Indian Ocean Territory',
	IQ: 'Iraqi',
	IR: 'Iranian',
	IS: 'Icelandic',
	IT: 'Italian',
	JE: 'Jersey',
	JM: 'Jamaican',
	JO: 'Jordanian',
	JP: 'Japanese',
	KE: 'Kenyan',
	KG: 'Kyrgyz',
	KH: 'Cambodian',
	KI: 'I-Kiribati',
	KM: 'Comoran',
	KN: 'Kittian and Nevisian',
	KP: 'North Korean',
	KR: 'South Korean',
	KW: 'Kuwaiti',
	KY: 'Cayman Islands',
	KZ: 'Kazakhstani',
	LA: 'Laotian',
	LB: 'Lebanese',
	LC: 'Saint Lucian',
	LI: 'Liechtensteiner',
	LK: 'Sri Lankan',
	LR: 'Liberian',
	LS: 'Mosotho',
	LT: 'Lithuanian',
	LU: 'Luxembourger',
	LV: 'Latvian',
	LY: 'Libyan',
	MA: 'Moroccan',
	MC: 'Monacan',
	MD: 'Moldovan',
	ME: 'Montenegrin',
	MF: 'Saint Martin (French part)',
	MG: 'Malagasy',
	MH: 'Marshallese',
	MK: 'Macedonian',
	ML: 'Malian',
	MM: 'Burmese',
	MN: 'Mongolian',
	MO: 'Macao',
	MP: 'Northern Mariana Islands',
	MQ: 'Martinique',
	MR: 'Mauritanian',
	MS: 'Montserrat',
	MT: 'Maltese',
	MU: 'Mauritian',
	MV: 'Maldivan',
	MW: 'Malawian',
	MX: 'Mexican',
	MY: 'Malaysian',
	MZ: 'Mozambican',
	NA: 'Namibian',
	NC: 'New Caledonia',
	NE: 'Nigerien',
	NF: 'Norfolk Island',
	NG: 'Nigerian',
	NI: 'Nicaraguan',
	NL: 'Dutch',
	NO: 'Norwegian',
	NP: 'Nepalese',
	NR: 'Nauruan',
	NU: 'Niue',
	NZ: 'New Zealander',
	OM: 'Omani',
	PA: 'Panamanian',
	PE: 'Peruvian',
	PF: 'French (French Polynesia)',
	PG: 'Papua New Guinea',
	PH: 'Filipino',
	PK: 'Pakistani',
	PL: 'Polish',
	PM: 'Saint Pierre and Miquelon',
	PN: 'Pitcairn',
	PR: 'Puerto Rico',
	PS: 'Palestinian Territory, Occupied',
	PT: 'Portuguese',
	PW: 'Palauan',
	PY: 'Paraguayan',
	QA: 'Qatari',
	RE: 'Reunion',
	RO: 'Romanian',
	RS: 'Serbian',
	RU: 'Russian',
	RW: 'Rwandan',
	SA: 'Saudi',
	SB: 'Solomon Islander',
	SC: 'Seychellois',
	SD: 'Sudanese',
	SE: 'Swedish',
	SG: 'Singaporean',
	SH: 'Saint Helena',
	SI: 'Slovenian',
	SJ: 'Svalbard and Jan Mayen',
	SK: 'Slovakian',
	SL: 'Sierra Leonean',
	SM: 'San Marinese',
	SN: 'Senegalese',
	SO: 'Somali',
	SR: 'Surinamer',
	SS: 'South Sudan',
	ST: 'Sao Tomean',
	SV: 'Salvadoran',
	SX: 'Sint Maarten (Dutch part)',
	SY: 'Syrian',
	SZ: 'Swazi',
	TC: 'Turks and Caicos Islands',
	TD: 'Chadian',
	TF: 'French (French Southern Territories)',
	TG: 'Togolese',
	TH: 'Thai',
	TJ: 'Tajik',
	TK: 'Tokelau',
	TL: 'East Timorese',
	TM: 'Turkmenistan',
	TN: 'Tunisian',
	TO: 'Tongan',
	TR: 'Turkish',
	TT: 'Trinidadian or Tobagonian',
	TV: 'Tuvaluan',
	TW: 'Taiwanese',
	TZ: 'Tanzanian',
	UA: 'Ukrainian',
	UG: 'Ugandan',
	UM: 'United States Minor Outlying Islands',
	US: 'American',
	UY: 'Uruguayan',
	UZ: 'Uzbekistani',
	VA: 'Holy See (Vatican City State)',
	VC: 'Saint Vincent and the Grenadines',
	VE: 'Venezuelan',
	VG: 'Virgin Islands, British',
	VI: 'Virgin Islands, U.S.',
	VN: 'Vietnamese',
	VU: 'Vanuatu',
	WF: 'Welsh',
	WS: 'Samoan',
	XK: 'Kosovo',
	YE: 'Yemenite',
	YT: 'Mayotte',
	ZA: 'South African',
	ZM: 'Zambian',
	ZW: 'Zimbabwean',
};
