import { Categories, LanguageCodeEnum } from 'src/constants';

export const typesSeed: {
	[K in Exclude<Categories, 'entities'>]: {
		[S in LanguageCodeEnum]?: string;
	}[];
} = {
	[Categories.Activity]: [
		{
			ar: 'تكنولوجيا المعلومات وتطوير البرمجيات',
			en: 'Information Technology and Software Development',
		},
		{ ar: 'الرعاية الصحية والطب', en: 'Healthcare and Medicine' },
		{ ar: 'الطاقة المتجددة', en: 'Renewable Energy' },
		{
			ar: 'التسويق الرقمي ووسائل التواصل الاجتماعي',
			en: 'Digital Marketing and Social Media',
		},
		{
			ar: 'التعليم عبر الإنترنت والتدريب',
			en: 'Online Education and Training',
		},
		{
			ar: 'الابتكار في التصنيع والتكنولوجيا',
			en: 'Innovation in Manufacturing and Technology',
		},
		{ ar: 'شركة الإطارات', en: 'Tire Manufacturing' },
		{
			ar: 'الاستدامة والحفاظ على البيئة',
			en: 'Sustainability and Environmental Conservation',
		},
		{ ar: 'السياحة والضيافة', en: 'Tourism and Hospitality' },
		{
			ar: 'الخدمات المالية والتكنولوجيا المالية',
			en: 'Financial Services and FinTech',
		},
	],
	[Categories.Advances]: [
		{ ar: 'تقدمات الزواج', en: 'Marriage Advances' },
		{ ar: 'تقدمات النقل', en: 'Transfer Advances' },
		{ ar: 'تقدمات الفوائد مُقدمًا', en: 'Benefits In Advance' },
		{ ar: 'تقدمات شخصية', en: 'Personal Advances' },
		{ ar: 'تقدمات الراتب', en: 'Salary Advances' },
	],
	[Categories.Allowances]: [
		{ ar: 'نقل', en: 'Transfer' },
		{ ar: 'سفر', en: 'Travel' },
		{ ar: 'مخاطر', en: 'Risk' },
		{ ar: 'سكن', en: 'Housing' },
		{ ar: 'التنقل', en: 'Commute' },
	],
	[Categories.BloodTypes]: [
		{ ar: 'A+', en: 'A+' },
		{ ar: 'A-', en: 'A-' },
		{ ar: 'B+', en: 'B+' },
		{ ar: 'B-', en: 'B-' },
		{ ar: 'O+', en: 'O+' },
		{ ar: 'O-', en: 'O-' },
		{ ar: 'AB+', en: 'AB+' },
		{ ar: 'AB-', en: 'AB-' },
	],
	[Categories.Bonuses]: [
		{ ar: 'مكافأة أداء', en: 'Performance Bonus' },
		{ ar: 'مكافأة التميز', en: 'Excellence Bonus' },
		{ ar: 'مكافأة سلوك', en: 'Behavior Bonus' },
		{ ar: 'مكافأة إنجاز', en: 'Achievement Bonus' },
		{ ar: 'مكافأة سنوية', en: 'Annual Bonus' },
		{ ar: 'مكافأة عيد الميلاد', en: 'Holiday Bonus' },
		{ ar: 'مكافأة تحفيز', en: 'Incentive Bonus' },
		{ ar: 'مكافأة تحقيق الأهداف', en: 'Goal Achievement Bonus' },
		{ ar: 'مكافأة تقدير', en: 'Appreciation Bonus' },
		{ ar: 'مكافأة توظيف', en: 'Hiring Bonus' },
	],
	[Categories.Commissions]: [
		{ ar: 'عمولة المبيعات', en: 'Sales Commission' },
		{
			ar: 'عمولة الحجز أو الحصول على عملاء جدد',
			en: 'New Business or Booking Commission',
		},
		{ ar: 'عمولة على الأداء', en: 'Performance Commission' },
		{
			ar: 'عمولة على تحسين الكفاءة أو التكاليف',
			en: 'Efficiency or Cost Improvement Commission',
		},
		{ ar: 'عمولة مشاريع خاصة', en: 'Project-specific Commission' },
	],
	[Categories.Contracts]: [
		{ ar: 'عقد دائم أو عقد دوام كامل', en: 'Permanent or Full-Time Contract' },
		{ ar: 'عقد محدد المدى أو مؤقت', en: 'Fixed-Term or Temporary Contract' },
		{ ar: 'عقد بدوام جزئي', en: 'Part-Time Contract' },
		{
			ar: 'عقد غير رسمي أو بدون ساعات محددة',
			en: 'Casual or Zero-Hour Contract',
		},
		{
			ar: 'اتفاقية العمل الحر أو المتعاقد المستقل',
			en: 'Freelance or Independent Contractor Agreement',
		},
		{ ar: 'اتفاقية الاستشارة', en: 'Consulting Agreement' },
		{ ar: 'اتفاقية التدريب المهني', en: 'Internship Agreement' },
		{ ar: 'عقد التجربة', en: 'Probationary Contract' },
		{ ar: 'عقد موسمي', en: 'Seasonal Contract' },
		{ ar: 'عقد العامل في وكالة التوظيف', en: 'Agency Worker Contract' },
		{
			ar: 'عقود العمل الحر أو اقتصاد الحرفة',
			en: 'Freelance or Gig Economy Contracts',
		},
	],
	[Categories.Deductions]: [
		{ ar: 'خصومات التأمين الاختيارية', en: 'Optional Insurance Deductions' },
		{ ar: 'ضريبة الدخل', en: 'Income Tax' },
		{ ar: 'التأمين الصحي', en: 'Health Insurance' },
		{ ar: 'التأمين الاجتماعي', en: 'Social Security Contributions' },
		{ ar: 'التبرعات الاجتماعية', en: 'Social Donations' },
		{ ar: 'صندوق التوفير', en: 'Savings Fund' },
	],
	[Categories.EmergencyRelationships]: [
		{ ar: 'أخت', en: 'Sister' },
		{ ar: 'أم', en: 'Mother' },
		{ ar: 'صديق', en: 'Friend' },
		{ ar: 'ابن العم/ابن الخال', en: 'Cousin' },
		{ ar: 'أب', en: 'Father' },
		{ ar: 'أخ', en: 'Brother' },
	],
	[Categories.Expenses]: [
		{ ar: 'نفقات السكن', en: 'Housing Expenses' },
		{ ar: 'تكاليف النقل', en: 'Transportation Costs' },
		{ ar: 'نفقات الترفيه', en: 'Entertainment Expenses' },
		{ ar: 'تكاليف التعليم', en: 'Education Costs' },
		{ ar: 'تكاليف الصحة', en: 'Healthcare Expenses' },
	],
	[Categories.FinancialComplaints]: [
		{ ar: 'مشاكل الفواتير', en: 'Billing Issues' },
		{ ar: 'المعاملات غير المصرح بها', en: 'Unauthorized Transactions' },
		{ ar: 'احتيال ببطاقة الائتمان', en: 'Credit Card Fraud' },
		{ ar: 'تناقضات في البيانات المالية', en: 'Discrepancies in Statements' },
		{ ar: 'شكاوى ذات صلة بالقروض', en: 'Loan-related Complaints' },
		{ ar: 'مشاكل مع خدمات البنك', en: 'Issues with Bank Services' },
		{ ar: 'شكاوى الاستثمارات', en: 'Investment Complaints' },
		{
			ar: 'النزاعات المتعلقة بمطالبات التأمين',
			en: 'Insurance Claim Disputes',
		},
		{ ar: 'شكاوى خدمة العملاء', en: 'Customer Service Complaints' },
		{ ar: 'مخاوف سرقة الهوية المالية', en: 'Identity Theft Concerns' },
	],
	[Categories.Installments]: [
		{ ar: 'تقسيط المرتب', en: 'Salary Installments' },
		{ ar: 'تقسيط القروض', en: 'Loan Installments' },
		{ ar: 'تقسيط المشتريات', en: 'Purchase Installments' },
		{ ar: 'تقسيط السيارة', en: 'Car Loan Installments' },
		{ ar: 'تقسيط التعليم', en: 'Education Installments' },
	],
	[Categories.PayrollDeductions]: [
		{ ar: 'تقاص الضرائب', en: 'Tax Deductions' },
		{ ar: 'خصم التأمين الصحي', en: 'Health Insurance Deductions' },
		{ ar: 'خصم التأمين الاجتماعي', en: 'Social Security Deductions' },
		{ ar: 'خصم التأمين على الحياة', en: 'Life Insurance Deductions' },
		{ ar: 'سداد القروض', en: 'Loan Repayments Deductions' },
	],
	[Categories.Permissions]: [],
	[Categories.Punctuates]: [],
	[Categories.Relations]: [
		{ ar: 'الأب', en: 'Father' },
		{ ar: 'الأم', en: 'Mother' },
		{ ar: 'الأخ', en: 'Brother' },
		{ ar: 'الأخت', en: 'Sister' },
		{ ar: 'الجد', en: 'Grandfather' },
		{ ar: 'الجدة', en: 'Grandmother' },
		{ ar: 'العم', en: 'Uncle' },
		{ ar: 'العمة', en: 'Aunt' },
		{ ar: 'الابن', en: 'Son' },
		{ ar: 'الابنة', en: 'Daughter' },
	],
	[Categories.Settlements]: [
		{ ar: 'تسوية قضائية', en: 'Legal Settlement' },
		{ ar: 'تسوية مالية', en: 'Financial Settlement' },
		{ ar: 'تسوية عقارية', en: 'Real Estate Settlement' },
		{ ar: 'تسوية تجارية', en: 'Business Settlement' },
		{ ar: 'تسوية محكمة', en: 'Court Settlement' },
		{ ar: 'تسوية زواج', en: 'Marital Settlement' },
		{ ar: 'تسوية تأمين', en: 'Insurance Settlement' },
		{ ar: 'تسوية أراضي', en: 'Land Settlement' },
		{ ar: 'تسوية أزمة', en: 'Crisis Settlement' },
		{ ar: 'تسوية مستقرة', en: 'Stable Settlement' },
	],
	[Categories.TrainingTypes]: [
		{ ar: 'تدريب تقني', en: 'Technical Training' },
		{ ar: 'تدريب المهارات الشخصية', en: 'Soft Skills Training' },
		{ ar: 'تدريب السلامة', en: 'Safety Training' },
		{ ar: 'تدريب القيادة', en: 'Leadership Training' },
		{ ar: 'تدريب مهارات الاتصال', en: 'Communication Skills Training' },
		{ ar: 'تدريب خدمة العملاء', en: 'Customer Service Training' },
		{ ar: 'تدريب المبيعات', en: 'Sales Training' },
		{ ar: 'تدريب إدارة المشاريع', en: 'Project Management Training' },
		{ ar: 'تدريب التنوع والاندماج', en: 'Diversity and Inclusion Training' },
		{ ar: 'تدريب إدارة الوقت', en: 'Time Management Training' },
	],
	[Categories.Vacations]: [
		{ ar: 'إجازة سنوية', en: 'Annual Leave' },
		{ ar: 'إجازة مرضية', en: 'Sick Leave' },
		{ ar: 'إجازة مدفوعة الأجر', en: 'Paid Time Off (PTO)' },
		{ ar: 'إجازة أمومة', en: 'Maternity Leave' },
		{ ar: 'إجازة أبوة', en: 'Paternity Leave' },
		{ ar: 'إجازة غير مدفوعة', en: 'Unpaid Leave' },
		{ ar: 'إجازات رسمية أو عطلات عامة', en: 'National or Public Holidays' },
		{ ar: 'إجازة دراسية', en: 'Study Leave' },
		{ ar: 'إجازة lلحداد', en: 'Bereavement Leave' },
		{ ar: 'إجازة بديلة للوقت الإضافي', en: 'Compensatory Time Off' },
	],
	[Categories.Visas]: [
		{ ar: 'تأشيرة سياحية', en: 'Tourist Visa' },
		{ ar: 'تأشيرة عمل أو تجارية', en: 'Business Visa' },
		{ ar: 'تأشيرة طالب', en: 'Student Visa' },
		{ ar: 'تأشيرة عمل', en: 'Work Visa' },
		{ ar: 'تأشيرة إقامة', en: 'Residence Visa' },
		{ ar: 'تأشيرة عبور أو عبور', en: 'Transit Visa' },
		{ ar: 'تأشيرة دبلوماسية', en: 'Diplomatic Visa' },
		{ ar: 'تأشيرة رسمية', en: 'Official Visa' },
		{ ar: 'تأشيرة للملتقى العائلي', en: 'Family Reunion Visa' },
		{ ar: 'تأشيرة للاجئ', en: 'Refugee Visa' },
	],
};

export const jobTitlesSeed: { [S in LanguageCodeEnum]?: string }[] = [
	{ ar: 'مدير الموارد البشرية', en: 'Human Resources Manager' },
	{ ar: 'مدير التسويق', en: 'Marketing Manager' },
	{ ar: 'مدير المبيعات', en: 'Sales Manager' },
	{ ar: 'مدير العمليات', en: 'Operations Manager' },
	{ ar: 'مدير الإنتاج', en: 'Production Manager' },
	{ ar: 'مدير المشتريات', en: 'Procurement Manager' },
	{ ar: 'محاسب مالي', en: 'Financial Accountant' },
	{ ar: 'محاسب تكاليف', en: 'Cost Accountant' },
	{ ar: 'محلل بيانات', en: 'Data Analyst' },
	{ ar: 'مهندس ميكانيكي', en: 'Mechanical Engineer' },
	{ ar: 'مهندس كهربائي', en: 'Electrical Engineer' },
	{ ar: 'مهندس برمجيات', en: 'Software Engineer' },
	{ ar: 'مسؤول تقنية المعلومات', en: 'IT Specialist' },
	{ ar: 'أخصائي تسويق رقمي', en: 'Digital Marketing Specialist' },
	{
		ar: 'أخصائي توظيف وتطوير الموارد البشرية',
		en: 'Recruitment and HR Development Specialist',
	},
	{ ar: 'مندوب مبيعات داخلية', en: 'Inside Sales Representative' },
	{ ar: 'مندوب مبيعات خارجية', en: 'Outside Sales Representative' },
	{ ar: 'موظف خدمة عملاء', en: 'Customer Service Representative' },
	{ ar: 'مساعد إداري', en: 'Administrative Assistant' },
	{ ar: 'محلل أعمال', en: 'Business Analyst' },
	{ ar: 'مصمم جرافيك', en: 'Graphic Designer' },
	{ ar: 'مصمم واجهات المستخدم', en: 'UI/UX Designer' },
	{ ar: 'مدير مشروع', en: 'Project Manager' },
	{ ar: 'أخصائي تجارة إلكترونية', en: 'E-commerce Specialist' },
	{ ar: 'أخصائي تواصل اجتماعي', en: 'Social Media Specialist' },
	{ ar: 'فني صيانة', en: 'Maintenance Technician' },
	{ ar: 'مراقب جودة', en: 'Quality Controller' },
	{ ar: 'سائق توصيل', en: 'Delivery Driver' },
	{ ar: 'مدير المشتريات', en: 'Purchasing Manager' },
	{ ar: 'موظف استقبال', en: 'Receptionist' },
	{ ar: 'أخصائي تسويق المحتوى', en: 'Content Marketing Specialist' },
	{ ar: 'محلل أمان المعلومات', en: 'Information Security Analyst' },
	{ ar: 'محلل تجربة المستخدم', en: 'User Experience Analyst' },
	{ ar: 'مدير المخزون', en: 'Inventory Manager' },
	{ ar: 'أخصائي علاقات عامة', en: 'Public Relations Specialist' },
	{ ar: 'محلل أداء الأعمال', en: 'Business Performance Analyst' },
	{ ar: 'مهندس شبكات', en: 'Network Engineer' },
	{ ar: 'أخصائي تطوير الأعمال', en: 'Business Development Specialist' },
	{ ar: 'أخصائي تقنية التشغيل', en: 'Operations Technology Specialist' },
	{ ar: 'مدير الشحن واللوجستيات', en: 'Shipping and Logistics Manager' },
	{ ar: 'مدير تكنولوجيا المعلومات', en: 'Information Technology Manager' },
	{ ar: 'محلل سلسلة التوريد', en: 'Customer Data Analyst' },
	{ ar: 'مدير العلاقات الحكومية', en: 'Government Relations Manager' },
	{ ar: 'أخصائي تصميم المنتج', en: 'Product Design Specialist' },
	{ ar: 'أخصائي تطوير البرمجيات', en: 'Software Development Specialist' },
	{ ar: 'مدير التدريب والتطوير', en: 'Training and Development Manager' },
	{ ar: 'مساعد مدير المشتريات', en: 'Assistant Purchasing Manager' },
	{
		ar: 'مندوب خدمة العملاء الفني',
		en: 'Technical Customer Service Representative',
	},
];

export const banksSeed: { [S in LanguageCodeEnum]?: string }[] = [
	{
		ar: 'البنك التجاري الدولي (CIB)',
		en: 'Commercial International Bank (CIB)',
	},
	{ ar: 'بنك مصر', en: 'Bank of Egypt' },
	{ ar: 'البنك الأهلي المصري', en: 'National Bank of Egypt' },
	{ ar: 'بنك القاهرة', en: 'Banque du Caire' },
	{ ar: 'بنك الإسكندرية', en: 'Bank of Alexandria' },
	{ ar: 'بنك البركة مصر', en: 'Baraka Bank Egypt' },
	{ ar: 'بنك الإنماء', en: 'Al-Inma Bank' },
	{
		ar: 'بنك الكويت الوطني (NBK) - مصر',
		en: 'National Bank of Kuwait (NBK) - Egypt',
	},
	{
		ar: 'البنك العربي الأفريقي الدولي (AAIB)',
		en: 'Arab African International Bank (AAIB)',
	},
	{ ar: 'بنك القاهرة الدولي', en: 'Cairo International Bank' },
	{
		ar: 'البنك الأهلي التجاري (الراجحي)',
		en: 'Al Rajhi Bank (Al Rajhi Commercial Bank)',
	},
	{ ar: 'مصرف الإنماء', en: 'Alinma Bank' },
	{ ar: 'مصرف الرياض', en: 'Riyadh Bank' },
	{ ar: 'البنك السعودي البريطاني (ساب)', en: 'Saudi British Bank (SABB)' },
	{ ar: 'بنك الجزيرة', en: 'Al Jazeera Bank' },
	{ ar: 'بنك البلاد', en: 'Al Bilad Bank' },
	{ ar: 'البنك العربي الوطني (العربي)', en: 'Arab National Bank (ANB)' },
	{ ar: 'بنك الجميع', en: 'Banque Saudi Fransi (BSF)' },
	{ ar: 'بنك الراجحي', en: 'Al Rajhi Bank (Al Rajhi Commercial Bank)' },
	{
		ar: 'بنك السعودي الفرنسي (بي.إن.بي باريبا)',
		en: 'Banque Saudi Fransi (BSF)',
	},
];
